package com.umeshowl.banking.investigation.compliance;
public enum ComplianceIndicatorType {
    MULTIPLE_HIGH_RISK_FINDINGS, FRAUD_CRITICAL, AML_CRITICAL, KYC_CRITICAL,
    FRAUD_AND_AML_COMBINATION, PEP_WITH_AML, HIGH_CONFIDENCE_MATCH,
    MULTIPLE_ESCALATIONS, CONSISTENT_HIGH_RISK_PATTERN, MANUAL_REVIEW_REQUIRED
}
