spring.application.name=banking-engineering-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/banking_platform
spring.datasource.username=banking_user
spring.datasource.password=banking_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
