spring.application.name=banking-engineering-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/banking_platform
spring.datasource.username=banking_user
spring.datasource.password=banking_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
