package com.umeshowl.banking.notification;

public enum NotificationType {
    CRITICAL_INVESTIGATION_CREATED,
    INVESTIGATION_ASSIGNED,
    INVESTIGATION_CLAIMED,
    INVESTIGATION_REASSIGNED,
    REPORT_GENERATED,
    INVESTIGATION_ESCALATED,
    AI_EXECUTION_FAILURE,
    INVESTIGATION_WAITING_TOO_LONG,
    OPENAI_FALLBACK_MODE
}
